### ISSUE TITLE
Not working on Chromebook

### ISSUE THREAD

**Issue by gbishop** [Kmoran1512/Math-Battle#41]
I click "Start Game" and see the board. I click on a minion and Buy Minion is enabled, but when I click on it nothing happens.

**Comment by gbishop** [comment]
Make a video of it in action so I can see how it is supposed to work.

**Comment by gbishop** [comment]
This was a problem with my chromebook.

**Comment by Kmoran1512** [comment]
Okay thank you.
Sorry It didn't work on your Chromebook.

If you would still like a video here is a link to one I added to our site:
https://kmoran1512.github.io/Math-Battle/report_video.html

**Comment by gbishop** [comment]
Working fine now. Cool game.

**Comment by Kmoran1512** [comment]
Thank you so much!
